name: Testing
run-name: Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup bin/ folder
      run: mkdir bin

    - name: Run tests
      run: make test