name: test
run-name: Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Project setup
      run: mkdir bin
      
    - name: Compile tests
      run: gcc -D TEST -g src/**.c tests/**.c main.c -I include -o bin/main.exe 
    
    - name: Run tests
      run: make test