name: test
run-name: Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run test 1
      run: make test-combat
    
    - name: Run test 2
      run: make test-entities-player
    
    - name: Run test 3
      run: make test-entities-player
